name: LXI-TOOLS-WIN64-BUILD-CHECK
on: [workflow_dispatch]

env:
  TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-check:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MSYS
          update: true
          install: git
      - name: CI-Build
        run: |
          echo 'Running in MSYS2!'
          bash msys2_scripts/msys2-lxi-tools-pacman.sh
          pacman -S --noconfirm mingw-w64-ucrt-x86_64-imagemagick
          meson setup liblxi/build liblxi
          meson compile -C liblxi/build
          meson install -C liblxi/build
          export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig:/ucrt64/lib/pkgconfig:$PKG_CONFIG_PATH
          meson setup lxi-tools/build lxi-tools
          meson compile -j 1 -C lxi-tools/build
          pacman -Rsc --noconfirm mingw-w64-ucrt-x86_64-imagemagick
          bash msys2_scripts/msys2-lxi-tools-redistributable.sh
          bash msys2_scripts/msys2-lxi-tools-create-exe.sh
