name: GHA-TEST
on: [workflow_dispatch]

jobs:
  build-release:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Upload windows x64
        run:
         gh workflow list
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
